list: $/spikedev/rentacar/models/location/columns.yaml
modelClass: Spikedev\Rentacar\Models\Location
title: Locations
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'spikedev/rentacar/locations/update/:id'
