list: $/spikedev/rentacar/models/vehicle/columns.yaml
modelClass: Spikedev\Rentacar\Models\Vehicle
title: Vehicles
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'spikedev/rentacar/vehicles/update/:id'
