list: $/spikedev/rentacar/models/reservation/columns.yaml
modelClass: Spikedev\Rentacar\Models\Reservation
title: Reservations
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'spikedev/rentacar/reservations/update/:id'
